version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated-update"
