name: CI Checks

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*" # Run on all branches

env:
  MIN_PYTHON_VERSION: 3.12

jobs:
  job-pre-commit-check:
    name: Pre-Commit Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Set up Python
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
        with:
          python-version: ${{ env.MIN_PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
        with:
          version: 0.5.20
          enable-cache: true

      - name: Install the project
        run: uv sync --only-dev

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

  job-image-processing-unit-tests:
    name: Image Processing Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Set up Python
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
        with:
          python-version: ${{ env.MIN_PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
        with:
          version: 0.5.20
          enable-cache: true

      - name: Install the project
        run: uv sync
        working-directory: image_processing

      - name: Run PyTest
        run: uv run pytest --cov=. --cov-config=.coveragerc
        working-directory: image_processing
